/*
 * Company: Tillotson
 * Effect Name: Hammond Chorus Vibrato
 * Description: A circuit simulation of the Hammond Scanner Vibrato. Effect by Mark Tillotson.
 *
 * This file was auto-generated by Aviate Audio Effect Creator for the Multiverse.
 */
#include <cmath>
#include "Aviate/LibBasicFunctions.h"
#include "ChorusVibrato.h"

using namespace Aviate;

namespace Tillotson_ChorusVibrato {

void ChorusVibrato::mapMidiControl(int parameter, int midiCC, int midiChannel)
{
    if (parameter >= NUM_CONTROLS) {
        return ; // Invalid midi parameter
    }
    m_midiConfig[parameter][MIDI_CHANNEL] = midiChannel;
    m_midiConfig[parameter][MIDI_CONTROL] = midiCC;
}

void ChorusVibrato::setParam(int paramIndex, float paramValue)
{
    switch(paramIndex) {
    case 0 : bypass( (paramValue - 0.000000) / (1.000000 - 0.000000) ); break;
    case 1 : volume( (paramValue - 0.000000) / (10.000000 - 0.000000) ); break;
    case 2 : mode( (paramValue - 0.000000) / (1.000000 - 0.000000) ); break;
    case 3 : depth( (paramValue - 1.000000) / (3.000000 - 1.000000) ); break;
    case 4 : mix( (paramValue - 0.000000) / (10.000000 - 0.000000) ); break;
    case 5 : led( (paramValue - 0.000000) / (1.000000 - 0.000000) ); break;
    default : break;
    }
}

float ChorusVibrato::getUserParamValue(int paramIndex, float normalizedParamValue)
{
    switch(paramIndex) {
    case 0 : return ( ((1.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // bypass
    case 1 : return ( ((10.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // volume
    case 2 : return ( ((1.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // mode
    case 3 : return ( ((3.000000 - 1.000000) * normalizedParamValue) + 1.000000 ); // depth
    case 4 : return ( ((10.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // mix
    case 5 : return ( ((1.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // led
    default : return 0.0f;
    }
}

void ChorusVibrato::processMidi(int channel, int control, int value)
{
    float val = (float)value / 127.0f;

    if ((m_midiConfig[Bypass_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Bypass_e][MIDI_CONTROL] == control)) {
        bypass(val);
        return;
    }

    if ((m_midiConfig[Volume_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Volume_e][MIDI_CONTROL] == control)) {
        volume(val);
        return;
    }

    if ((m_midiConfig[Mode_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Mode_e][MIDI_CONTROL] == control)) {
        mode(val);
        return;
    }

    if ((m_midiConfig[Depth_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Depth_e][MIDI_CONTROL] == control)) {
        depth(val);
        return;
    }

    if ((m_midiConfig[Mix_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Mix_e][MIDI_CONTROL] == control)) {
        mix(val);
        return;
    }

    if ((m_midiConfig[LED_e][MIDI_CHANNEL] == channel) && (m_midiConfig[LED_e][MIDI_CONTROL] == control)) {
        led(val);
        return;
    }

}

audio_block_t* ChorusVibrato::m_basicInputCheck(audio_block_t* inputAudioBlock, unsigned outputChannel)
{
    // Check if effect is disabled
    if (m_enable == false) {
        // do not transmit or process any audio, return as quickly as possible after releasing the inputs
        if (inputAudioBlock) { release(inputAudioBlock); }
        return nullptr; // disabled, no further EFX processing in update()
    }  // end of enable check

    // check if effect is in bypass
    if (m_bypass == true) {
        // drive input directly to the specified output. ie. bypass
        if (inputAudioBlock != nullptr) {
            // valid input, drive to outputChannel if specified
            if (outputChannel >= 0) {
                transmit(inputAudioBlock, outputChannel); // drive to specified output
            }
            release(inputAudioBlock); // release the input block as we are done with it
        } else { // invalid input block, allocate a block and drive silence if specified
            if (outputChannel >= 0) {
                audio_block_t* silenceBlock = allocate();
                if (silenceBlock) {
                    clearAudioBlock(silenceBlock);  // create silence in the buffer
                    transmit(silenceBlock, outputChannel);
                    release(silenceBlock);
                }
            }
        }
        return nullptr;  // bypassed, no further EFX processing in update()
    }  // end of bypass check

    // If not disabled or bypassed, create silence if the input block is invalid then
    // return the valid audio block so update() can continue.
    if (inputAudioBlock == nullptr) {
        inputAudioBlock = allocate();
        if (inputAudioBlock == nullptr) { return nullptr; } // check if allocate was unsuccessful
        // else
        clearAudioBlock(inputAudioBlock);
    }
    return inputAudioBlock; // inputAudioBLock is valid and ready for update() processing
}

const uint8_t rblk[256] = { 0x6e, 0x84, 0x2c, 0xc6, 0x25, 0xbf, 0xe3, 0x3e, 0xce, 0xfa, 0xdb, 0xfa, 0x2f, 0xda, 0x2d, 0x67, 0xea, 0x3f, 0x4c, 0x53, 0x37, 0x5b, 0x73, 0x15, 0x01, 0x89, 0x92, 0x84, 0xfd, 0x8e, 0x0e, 0x28, 0xfe, 0x68, 0x15, 0x60, 0x5b, 0xb1, 0xef, 0xbf, 0x89, 0xf1, 0xc7, 0x5f, 0x4c, 0x46, 0x58, 0xb7, 0xb3, 0xa3, 0x05, 0x08, 0x68, 0xf6, 0x88, 0x41, 0x57, 0x50, 0xc4, 0x3f, 0xea, 0xb0, 0x98, 0x03, 0x50, 0x6c, 0x33, 0x79, 0x10, 0x89, 0x12, 0xe5, 0xe6, 0xba, 0x9f, 0xd5, 0x90, 0xe0, 0xc1, 0x7b, 0xc6, 0x17, 0x32, 0xcc, 0xe3, 0xc1, 0x36, 0x2c, 0x30, 0x16, 0x3f, 0xd1, 0x82, 0xd9, 0xcb, 0x44, 0x01, 0xf9, 0x05, 0xdc, 0x18, 0x36, 0x2e, 0x58, 0x6c, 0x9b, 0xf1, 0x0b, 0xf4, 0x02, 0x69, 0x12, 0xa3, 0x44, 0xa3, 0x84, 0x16, 0xd6, 0xd6, 0xf6, 0xe6, 0x46, 0x02, 0x34, 0x86, 0xf6, 0x27, 0x57, 0x37, 0x02, 0x65, 0x96, 0x26, 0x27, 0x16, 0x47, 0xf6, 0x00, 0x28, 0xf3, 0x3a, 0x0b, 0x95, 0x5b, 0x5d, 0xe4, 0x98, 0x63, 0x2a, 0xf8, 0xb7, 0xb3, 0x5c, 0x67, 0x8f, 0x9b, 0x85, 0x23, 0x98, 0xa3, 0xcf, 0x7a, 0xb6, 0x97, 0x1b, 0xda, 0x51, 0x37, 0xd8, 0x79, 0x2a, 0x13, 0x84, 0xbf, 0x6e, 0xe1, 0xa4, 0x06, 0x44, 0xce, 0xfe, 0xfc, 0x81, 0x5a, 0x63, 0x10, 0xf5, 0xe9, 0x34, 0x8d, 0x8c, 0x03, 0x07, 0x42, 0x9b, 0x23, 0x1c, 0xec, 0x5a, 0xf5, 0x65, 0x85, 0x08, 0xe9, 0x44, 0x76, 0xca, 0xe8, 0x7c, 0x0e, 0xb6, 0x7b, 0x0a, 0x37, 0xd5, 0x6e, 0x48, 0xcb, 0x57, 0x7c, 0x58, 0xe3, 0x7f, 0x60, 0x26, 0x1a, 0x83, 0x42, 0x06, 0xdd, 0x37, 0x6b, 0x62, 0x3f, 0x54, 0xa7, 0xb5, 0x1e, 0x8f, 0x32, 0x2d, 0x46, 0xad, 0x37, 0x7d, 0x82, 0xa5, 0xc5, 0x4d, 0xfc, 0x41, 0xa6, 0xe0, 0xc1, 0x06, 0x06};
const uint8_t* ChorusVibrato::getRblk() { return rblk; }
static constexpr char PROGMEM ChorusVibrato_name[] = {0x54, 0x69, 0x6c, 0x6c, 0x6f, 0x74, 0x73, 0x6f, 0x6e, 0x3a, 0x44, 0x3a, 0x48, 0x61, 0x6d, 0x6d, 0x6f, 0x6e, 0x64, 0x20, 0x43, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x20, 0x56, 0x69, 0x62, 0x72, 0x61, 0x74, 0x6f, 0x0};
const char* ChorusVibrato::getName() { return ChorusVibrato_name; }

}
