/*
 * Company: Tillotson
 * Effect Name: Hammond Chorus Vibrato
 * Description: A circuit simulation of the Hammond Scanner Vibrato. Effect by Mark Tillotson.
 *
 * This file was auto-generated by Aviate Audio Effect Creator for the Multiverse.
 */
#include <cmath>
#include "Aviate/LibBasicFunctions.h"
#include "ChorusVibrato.h"

using namespace Aviate;

namespace Tillotson_ChorusVibrato {

void ChorusVibrato::mapMidiControl(int parameter, int midiCC, int midiChannel)
{
    if (parameter >= NUM_CONTROLS) {
        return ; // Invalid midi parameter
    }
    m_midiConfig[parameter][MIDI_CHANNEL] = midiChannel;
    m_midiConfig[parameter][MIDI_CONTROL] = midiCC;
}

void ChorusVibrato::setParam(int paramIndex, float paramValue)
{
    switch(paramIndex) {
    case 0 : bypass( (paramValue - 0.000000) / (1.000000 - 0.000000) ); break;
    case 1 : volume( (paramValue - 0.000000) / (10.000000 - 0.000000) ); break;
    case 2 : mode( (paramValue - 0.000000) / (1.000000 - 0.000000) ); break;
    case 3 : depth( (paramValue - 1.000000) / (3.000000 - 1.000000) ); break;
    case 4 : mix( (paramValue - 0.000000) / (10.000000 - 0.000000) ); break;
    case 5 : led( (paramValue - 0.000000) / (1.000000 - 0.000000) ); break;
    default : break;
    }
}

float ChorusVibrato::getUserParamValue(int paramIndex, float normalizedParamValue)
{
    switch(paramIndex) {
    case 0 : return ( ((1.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // bypass
    case 1 : return ( ((10.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // volume
    case 2 : return ( ((1.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // mode
    case 3 : return ( ((3.000000 - 1.000000) * normalizedParamValue) + 1.000000 ); // depth
    case 4 : return ( ((10.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // mix
    case 5 : return ( ((1.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // led
    default : return 0.0f;
    }
}

void ChorusVibrato::processMidi(int channel, int control, int value)
{
    float val = (float)value / 127.0f;

    if ((m_midiConfig[Bypass_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Bypass_e][MIDI_CONTROL] == control)) {
        bypass(val);
        return;
    }

    if ((m_midiConfig[Volume_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Volume_e][MIDI_CONTROL] == control)) {
        volume(val);
        return;
    }

    if ((m_midiConfig[Mode_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Mode_e][MIDI_CONTROL] == control)) {
        mode(val);
        return;
    }

    if ((m_midiConfig[Depth_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Depth_e][MIDI_CONTROL] == control)) {
        depth(val);
        return;
    }

    if ((m_midiConfig[Mix_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Mix_e][MIDI_CONTROL] == control)) {
        mix(val);
        return;
    }

    if ((m_midiConfig[LED_e][MIDI_CHANNEL] == channel) && (m_midiConfig[LED_e][MIDI_CONTROL] == control)) {
        led(val);
        return;
    }

}

audio_block_t* ChorusVibrato::m_basicInputCheck(audio_block_t* inputAudioBlock, unsigned outputChannel)
{
    // Check if effect is disabled
    if (m_enable == false) {
        // do not transmit or process any audio, return as quickly as possible after releasing the inputs
        if (inputAudioBlock) { release(inputAudioBlock); }
        return nullptr; // disabled, no further EFX processing in update()
    }  // end of enable check

    // check if effect is in bypass
    if (m_bypass == true) {
        // drive input directly to the specified output. ie. bypass
        if (inputAudioBlock != nullptr) {
            // valid input, drive to outputChannel if specified
            if (outputChannel >= 0) {
                transmit(inputAudioBlock, outputChannel); // drive to specified output
            }
            release(inputAudioBlock); // release the input block as we are done with it
        } else { // invalid input block, allocate a block and drive silence if specified
            if (outputChannel >= 0) {
                audio_block_t* silenceBlock = allocate();
                if (silenceBlock) {
                    clearAudioBlock(silenceBlock);  // create silence in the buffer
                    transmit(silenceBlock, outputChannel);
                    release(silenceBlock);
                }
            }
        }
        return nullptr;  // bypassed, no further EFX processing in update()
    }  // end of bypass check

    // If not disabled or bypassed, create silence if the input block is invalid then
    // return the valid audio block so update() can continue.
    if (inputAudioBlock == nullptr) {
        inputAudioBlock = allocate();
        if (inputAudioBlock == nullptr) { return nullptr; } // check if allocate was unsuccessful
        // else
        clearAudioBlock(inputAudioBlock);
    }
    return inputAudioBlock; // inputAudioBLock is valid and ready for update() processing
}

const uint8_t rblk[256] = TEENSY_AUDIO_BLOCK;
const uint8_t* ChorusVibrato::getRblk() { return rblk; }
static constexpr char PROGMEM ChorusVibrato_name[] = {0x54, 0x69, 0x6c, 0x6c, 0x6f, 0x74, 0x73, 0x6f, 0x6e, 0x3a, 0x48, 0x61, 0x6d, 0x6d, 0x6f, 0x6e, 0x64, 0x20, 0x43, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x20, 0x56, 0x69, 0x62, 0x72, 0x61, 0x74, 0x6f, 0x0};
const char* ChorusVibrato::getName() { return ChorusVibrato_name; }

}
